---
abstract: 'Class for searching http://galerie-ilonka.cz .'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Search-GalerieIlonkaCZ
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  LWP::UserAgent: 0
  Readonly: 0
  WWW::Search: 0
  Web::Scraper: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Search-GalerieIlonkaCZ
  homepage: https://github.com/tupinek/WWW-Search-GalerieIlonkaCZ
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/WWW-Search-GalerieIlonkaCZ
version: 0.01
